### ISSUE TITLE
With OpenFeign, why doesn't the timeout set by hystrix take effect?

### ISSUE THREAD

**Issue by Felfan** [OpenFeign/feign#1050]
i use openFeign,set the property for example:
```
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    key#method(): 
      fallback:
        enabled: true
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
```
