### ISSUE TITLE
Logback configuration error detected when using openFeign

### ISSUE THREAD

**Issue by JoniSykes** [OpenFeign/feign#1052]
Trying to use openFeign as our rest client. 
Followed the various guides online to set up. Tried using slf4j plugin too.
No matter what I try AppContext won't load and I see the following error:

```Caused by: java.lang.IllegalStateException: Logback configuration error detected:

ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [loggingAppender_IS_UNDEFINED]. Did you define it below instead of above in the configuration file?
```

application.yaml:

```
logging.level.com.moneysupermarket.energyrequoteconsumer.token.TokenServiceClient: DEBUG

feign:
  client:
    config:
      TokenServiceClient:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
```

service:
```
    public TokenService(...) {
        ...
        this.client = Feign.builder()
                .decoder(new GsonDecoder())
                .logger(new Slf4jLogger(TokenServiceClient.class))
                .target(TokenServiceClient.class, baseURL);
    }

    public String getAutoLoginToken(...) {
        ...
        return client.getToken(request);
    }
```

client:
```
@FeignClient(value = "tokenServiceClient")
public interface TokenServiceClient {
    @RequestMapping(method = RequestMethod.POST, value = "/tokens")
    @Headers("Content-Type: application/json")
    String getToken(AutoLoginTokenRequest request);
}
```

build.gradle
```
...
"org.springframework.cloud:spring-cloud-starter-openfeign:2.1.2.RELEASE",
"org.springframework.cloud:spring-cloud-dependencies:Greenwich.SR2",
"com.netflix.feign:feign-gson:7.2.1",
"io.github.openfeign:feign-slf4j:10.3.0"
```
