### ISSUE TITLE
Inquiries about setting timeout related to 'feign'

### ISSUE THREAD

**Issue by J-minkuk** [OpenFeign/feign#1354]
1. ribbon connect timeout is meaningful when retrieving server information from Eureka?
```
ribbon:
  ConnectTimeout: 1500
  ReadTimeout: 10000
```

2. feign connection(http-client) timeout is meaningful when establishing a connection before calling 'B domain' in 'A domain'?
```
feign:
#  httpclient:
#    connection-timeout: 1
#    max-connections: 1
#    max-connections-per-route: 1
#    time-to-live: 900
#    time-to-live-unit: milliseconds
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 1
        readTimeout: 1000
```

3. What is the difference between 'feign.httpclient. ...' and 'feign.client.config. ...' ?

I'll be looking forward to your prompt reply.
