### ISSUE TITLE
OpenFeign Client Timeout Not Working Despite Configuration

### ISSUE THREAD

**Issue by gordonjun2** [OpenFeign/feign#2776]
**Description:**
I have configured Feign client timeouts as follows:

```
feign:
  client:
    config:
      default:
        readTimeout: 10000
        connectTimeout: 10000
  circuitbreaker:
    enabled: true
```

I expect the Feign client to only time out after 10 seconds, but I am experiencing timeout exceptions after only 1 second, even though my application simulates a delay of 5 seconds:

```
@FeignClient(name = "${client.inventory.name}", url = "${client.inventory.url}", configuration = InventoryClientConfig.class, fallbackFactory = InventoryClientFallbackFactory.class)
public interface InventoryClient {

    @GetMapping("/api/inventory/isInStock")
    Boolean isInStock(@RequestParam String skuCode, @RequestParam Integer quantity);
}
```

```
@GetMapping("/isInStock")
public Boolean isInStock(@RequestParam String skuCode, @RequestParam Integer quantity) throws InterruptedException {
    if (skuCode == null || quantity == null) {
        throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Invalid request parameters");
    }

    Thread.sleep(5000);

    log.info("Received inventory check request for skuCode: {}", skuCode);

    try {
        return inventoryService.isInStock(skuCode, quantity);
    } catch (Exception e) {
        log.error("InventoryController.isInStock Exception", e);
        return null;
    }
}
```

Despite the 10s timeout configuration, I get the following timeout exception after 1s:

```
2025-02-14 15:55:09.040 DEBUG [order-service] i.g.r.t.internal.TimeLimiterImpl : Event TIMEOUT published: 2025-02-14T15:55:09.040+08:00[Asia/Singapore]: TimeLimiter 'InventoryClient#isInStock(String,Integer)' recorded a timeout exception.
...
java.util.concurrent.TimeoutException: TimeLimiter 'InventoryClient#isInStock(String,Integer)' recorded a timeout exception.
...
2025-02-14 15:55:09.049 DEBUG [order-service,61b019d1e5552416,61b019d1e5552416] 27098 --- [nio-8081-exec-1] i.g.r.c.i.CircuitBreakerStateMachine     : Event ERROR published: 2025-02-14T15:55:09.049+08:00[Asia/Singapore]: CircuitBreaker 'InventoryClient#isInStock(String,Integer)' recorded an error: 'java.util.concurrent.TimeoutException: TimeLimiter 'InventoryClient#isInStock(String,Integer)' recorded a timeout exception.'. Elapsed time: 1007 ms
2025-02-14 15:55:09.053  INFO [order-service,61b019d1e5552416,23b69fa79c5c8046] 27098 --- [nio-8081-exec-1] c.g.m.o.f.InventoryClientFallbackFactory : Fallback from isInStock... Cause: TimeLimiter 'InventoryClient#isInStock(String,Integer)' recorded a timeout exception.
```

I came across an article (https://segmentfault.com/a/1190000041228958/en) suggesting that the 1s timeout might be due to Ribbon (since OpenFeign integrates with Ribbon).
However, the solution stated in the article is to add the same configuration as above, yet the issue persists.

**Version:**
- Spring Boot Version: 2.7.18
- Java Version: 1.8
- Spring Cloud Version: 2021.0.3

**Relevant Dependencies Added:**
- ```spring-cloud-starter-openfeign```
- ```spring-cloud-starter-circuitbreaker-resilience4j```

I greatly appreciate any help on this.

**Comment by gordonjun2** [comment]
Update:

I managed to solve this issue. The problem is located in my feign's configuration.

```
feign:
  client:
    config:
      default:
        readTimeout: 10000
        connectTimeout: 10000
  circuitbreaker:
    enabled: true
```

I need to change the 'default' to match my FeignClient's name set up at

```
@FeignClient(name = "${client.inventory.name}", url = "${client.inventory.url}", configuration = InventoryClientConfig.class, fallbackFactory = InventoryClientFallbackFactory.class)
public interface InventoryClient {

    @GetMapping("/api/inventory/isInStock")
    Boolean isInStock(@RequestParam String skuCode, @RequestParam Integer quantity);

}
```

where ```${client.inventory.name}``` is configured as

```
client:
  inventory:
    name: inventory
    url: http://localhost:8082
```

Therefore, the correct configuration for my Feign is

```
feign:
  client:
    config:
      inventory:
        readTimeout: 10000
        connectTimeout: 10000
  circuitbreaker:
    enabled: true
```

To give a bit more context, I am using resilience4j as well, and my configuration for my resilience4j is

```
resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 10000ms
        cancel-running-future: true
```

Notice that for resilience4j, I can still use the 'default'.

Also, my dependency for openfeign is

```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-openfeign</artifactId>
			<version>3.1.4</version>
		</dependency>
```
