### ISSUE TITLE
Move to a new org

### ISSUE THREAD

**Issue by adriancole** [OpenFeign/feign#373]
Netflix was the original sponsor of Feign, but it isn't used internally anymore. Plus, since we aren't in an org, we have no place to host things like jaxrs2 or other optional repositories.

I think we have sufficient activity to carry-on, so should we move on to a new org?

**Comment by kennedyoliveira** [comment]
@adriancole, off topic but just for curiosity, what is Netflix using instead of Feign?

**Comment by adriancole** [comment]
Due to freedom+responsibility, I imagine there are multiple answers to
this. One thing I noticed recently was Ribbon
<https://github.com/Netflix/ribbon/blob/master/ribbon-examples/src/main/java/com/netflix/ribbon/examples/rx/proxy/MovieService.java>,
which has declarative annotations. There are probably non-netflix projects
in-use, too. Folks currently working at Netflix are free to chime in, as
they'd know better than me what's working for them.

**Comment by adriancole** [comment]
Perhaps corny, but what if we used https://github.com/feigntown? Basically, it would be the place where all the feign projects hangout.

**Comment by xxlabaza** [comment]
Sounds cool. What shall I do to get in?

**Comment by adriancole** [comment]
It needs to be created first, and probably needs a few more acks before we
proceed.

**Comment by pmvilaca** [comment]
As feign isn't used internally anymore, will Netflix continue supporting it or it'll managed by the community?

**Comment by spencergibb** [comment]
@pmvilaca, it wasn't ever heavily used at Netflix. @adriancole created it while he was there for another project (denominator) and has been maintained by him since he left. Moving out of Netflix will allow for more community involvement.

**Comment by adriancole** [comment]
https://github.com/FeignTown it is then!

We'll keep this open until it is functional

**Comment by adriancole** [comment]
so first steps is we need to get some infrastructure in place. For example, publishing requires a bunch of work on the sonatype and bintray side of things, then we'd need to update the build to use it.

First decisions are about group id and bintray id. For example, we could use feign.io, but we should probably do the DNS registration (esp helpful if someone offers to steward that domain and grant access to admins of the org).

WRT the build switch to use an alternative release pipeline, I'm far better at this in maven than gradle. For example, I've some very good pipelines setup for zipkin that use bintray and have release-based tags that work really well. I can easily troubleshoot these when anything goes wrong, etc. This includes the maven wrapper, so everything is nice and repeatable, pinned to specific versions etc. If folks are open to a build-switch, I could make light work out of the move, reusing efforts I've done elsewhere. Otherwise, it is also fine, just would be delayed further.

**Comment by spencergibb** [comment]
I'm happy with feign.io (or even feign.github.io). I'm also ok with moving to maven. I'm in the same boat as you.

**Comment by adriancole** [comment]
ahh didn't think about feign.github.io. Less things to manage and I suppose sonatype would accept that, too (except it would have to be feigntown.github.io as someone's using feign)...

on that note.. @Feign, if you are listening, would you mind yielding your id to the org feign?

**Comment by spencergibb** [comment]
Right, forgot about that.

**Comment by velo** [comment]
FWIW, I created the following plugins:
https://github.com/velo/feign-mock
https://github.com/velo/feign-jackson1

I also wrote 2 blog posts about it...
https://velo.github.io/2016/06/05/Testing-feign-clients.html
https://velo.github.io/2016/05/28/Zero-effort-A-P-I-client.html

**Comment by adriancole** [comment]
Great stuff. I'm out for a couple weeks on holiday, and can pick this up
when I get back unless someone else beats me to it.

**Comment by spencergibb** [comment]
Suggestion for openfeign instead of feigntown.

**Comment by adriancole** [comment]
no problem on openfeign

**Comment by adriancole** [comment]
I created a dummy repository so that we can setup things like Sonatype. We can drop this once we are ready to migrate. https://github.com/OpenFeign/feign

**Comment by adriancole** [comment]
here's a sonatype issue https://issues.sonatype.org/browse/OSSRH-23228

**Comment by adriancole** [comment]
added https://bintray.com/openfeign/maven/feign/view and requested jcenter/jfrog

**Comment by adriancole** [comment]
sonatype issue was resolved

**Comment by adriancole** [comment]
NEXT STEP:
make a branch here based on https://github.com/Netflix/feign/pull/404, force push it to openfeign/feign and test things like travis and jfrog snapshots

**Comment by adriancole** [comment]
I can grind some of this tomorrow (friday)

**Comment by adriancole** [comment]
ok I've temporarily forked feign (after merging maven configuration) to the OpenFeign org.

Next steps:
Setup travis on the fork to test things

**Comment by adriancole** [comment]
testing by cherry-picking 9fd832cfca3a93a35483ba65991937ff5b71b5cb onto the fork and adding the below file, missing from the commit.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                          http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>sonatype</id>
      <username>${env.SONATYPE_USER}</username>
      <password>${env.SONATYPE_PASSWORD}</password>
    </server>
    <server>
      <id>bintray</id>
      <username>${env.BINTRAY_USER}</username>
      <password>${env.BINTRAY_KEY}</password>
    </server>
    <server>
      <id>jfrog-snapshots</id>
      <username>${env.BINTRAY_USER}</username>
      <password>${env.BINTRAY_KEY}</password>
    </server>
    <server>
      <id>github.com</id>
      <username>${env.GH_USER}</username>
      <password>${env.GH_TOKEN}</password>
    </server>
  </servers>
</settings>
````

**Comment by adriancole** [comment]
looks like jfrog snapshot hosting wasn't completely setup. I clicked to request it from  https://bintray.com/openfeign/maven/feign

**Comment by adriancole** [comment]
hoping we can sort this by next week

**Comment by adriancole** [comment]
used wrong credentials for the openfeign org. testing the following ones, now.

```yaml
env:
  global:
  # Ex. travis encrypt BINTRAY_USER=your_github_account
  - secure: "GB5nPtjTvfrPIUhPZzJst+oDxy/QD6d0qRiJbfAhnYfwjJAmLviXWEgZL3cvK7Cb6MjnuBesC8dit2hdqV42lUektvZScuNiY02HJogjP6EqUgkmRCngD+Xp6Tjalj1s7VKtDB+QFYyQrD+SKTpVI5hbnFaTU+SnCqFz44PZjI4FksnvU7zoWCvJcaKw9N36Z+i3J9XkzMyxDoJh
6Q8vyOs21eqeE0dKB1ryHb7v8wa93i8/4dAmi0NXJock4F7XsLn36vAfmCQ809JKJrS1oADHN8CIIk3dFkRnmsRBKYfaVu8ti/hFx0hGGx3wvoDbyn81XZrf8krXziEYBdwcumDmEJiMf5Suacbu17k8XIUlJUbHLAqjmnUKX7EBaE7MnG4T44ZNpJAynAihcqx78015x5gUDFE/gGBW+KODlwvLl
eR+kUiJegnWK9Z5K/iG7VTp5dKyJ8//5AWbZaGQsHbV1Zrf935zJZOmkDctsLlBvq/EXQoF7rqmySQKowIQrxfRYDcWZLLv0ofItetVJBww0pT4P1fdRV8xeVP/RuecA8wjB5oQkFyy8Cpi1fqKN6sRKSkdcqSOEt553Ai8bJJ9JPwSo0qpthHXLuBrkJhzXoMluPz4qC6/x+adzn17a4r0Zecz09
lExXThKhvFBmB4yksnrRQQlLAzEkSrb0g="
  # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: "SlnGkgY8eT+G4mKIQc4L45iX6eIS8c6bSnGDbcpWVl5/jb99zYYrRAhffMfN+p6pXKj7KiojOTbo0D++JyiHI0x9h1+HPQuER3xCuYSniGWIB1Ao8VTncPpq/3ro6jg2A4qHnk3dVsvzsEvNBvNHu/37pMm1LkLWCQH19NCXj/3uuqPylmryEbwuG5q3JqHUdsXWn+LXAPmHTO38
Idj9Lbgue5ocre2uIHLypDQbv7/74k9MQMvk9m4l7X96a3K4dOomU+3KzYTPbFwnS7LnsZ3S0ztHLJ8O4/scqWOUMlWcTHm7sHcVP9GBZ6bj0wz7+8cYIr6ZanorPbfz+eoeu7ANPK6ARkxTDtEp5GBOYUGQ3EKTPeC5tVhm6Hs7tsd0oJyCPzV6kAd0lecDFRFWherqSpdW/zOtU7WzHyO8WhTja
H8ISetPbSegmzHLkVw436dbPgXDhwC92P849pIVwi4DrloQKN8vs9FNEdT7bFYlzkhoKDdxmHb85qzdvTMKv2Z49VhSLQPoKE0IEeqy5AEUWnuNcbnS8viclm4K2HGJlHmg9xcnDaS3lTRPNEVTZssnjaE0t5BHtHuGOiXfY4ZVSco1NoZmmlbCJShAkbFLHrQXAhQAmPWZGpzGqjz4AkHavsBCLDQ6O/IXmyIVYV/UE1EBh/jfFvXOcsGNA98="
  # Ex. travis encrypt GH_USER_EMAIL=for_github@domain.com --add
  - secure: "oDiMvNeql7jCwGko1njuLUV1W55dDaeMbjFcxPFDD1Y2Df+t+AEa+5UuTdalLP82Kcas0GaV8pBaf0HtJR96yqCnPpGNeoYYKTl5pqT/sBCPoTAu7WYWSPAuEb201anSNgioMxPanWemenrijSTnOCCtl8WyGqrIJMz95UpnmL2bj38D+s5KXr8jm6bOe4arPMvsqeKin9KSoTuIn3Nc4JwEWfoYeLMCD78L7sjZn+5WaA6Sc1DarRf5hHhGp/LVDFzDHJ4KVWsaG8erBehj8p12ifcPaxZFJS+FgjvUIHV4sYPCZy28fttCsRX+NAXWQyYXuQizSTkz/ozt+TNta3JQBQVVvmFcUMOfW95EH6ovwLHJHsUfpRNtuOh1uu6ed2VBCHQ02V0zj0vmAhZWWVRWDQR6/FIewhzyclE9uGoCjmascbjV9E5V+ZaCSNU6msgexf9f52uHdrfRIALucfJumm597ouLzZycomYtttPSVd48V6up4lqm1o6dKIpcHY0lpRlE958yOFNcCeCiEgGjeA4oxrfWSSPwkBEwtZn51hke3t8F1f5JdV89t1vkShp6PYfDgeNbDqYexhoNM/zxPyj8pPZi3+T6zp5UflPhgTeTVx/cibJlpHuoxAkW0GKyNBTzk6u4NfsPnJWeihAqtMZ1w7kv58j30qR+9cY="
  # Ex. travis encrypt GH_USER=your_github_account --add
  - secure: "G3sZ6UUVL9Adwu6G0J08YdnVKXGPVSto/Y6EKPuxhywOnESEgbS/UVrP5UL87zLt0wlCLfPybivkbRomaA2W82gmwnsY2O6vxzULYpywADpvD+wkG1aPG20egcYtETSEoKGQec+0iY0nSHUeJXit7wMdDs59rcsMA9NuYPXQp+hemf4cN1wrof0o6wpi70d8qgqhkEVdpSBkfattDtIAxKUj+bsKqcN6WCUQpAGQDoyetJ2OZySehhldis5r8sPJBgk1sNlcwIRVV701sbV94QkeOIZ0T60sLlaQeG5D+/H1Kdx+z788CdU3/6aMhiT5osKbAh/HgNh1au9jlFpWYODbE8VXAqUg9JQvu4R4dtNTN5uFEXDCO+uXuv8kHO+GS9dYt63xwz2WRZ3UDr5JcHgfWyndQoiP5eJq35rG++hX4Sd3yjq/Ks4rBETaVfP4FzCz0AePsOX9omoVw+wVS+XOOE4k3aJpYksqaX5MKu7xsVC16v28ZejBXOB4AspBrxvUhM17RwvZYmbuy0QD9tUQI5aEoDimShGY20VWd2XKf8FR4sx/RxRG0iNtL8vtvnEA3M8a0ktFy73zstOnHSItCWGuRtGvMo/f7cT3uH2NfjnvVVeelB5r+cgZcDc1RllRISbv495voQyzyEPIW3EvU/LVtpsfhAOF5nv54wI="
  # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
  - secure: "AmgKwBBbSCJKvTvuRtbqCqEz5jBABwXMUZBmdMjvfN2fFhEKHSGj5JAYrKYUbatDbH1GlI+j1Ep/Asgq0bH5oFGQ32p5xeHgZsmDNVO/QuW5E97YMHZfOfiWMxnq3Vh5PwLVZOqKwteK44V5IDcslHW+0Dqe/0a6aL5UotmzswOsbRW0xgtjKQaJn9VnRT9SjAlJ3jiowVcPkS7e/uKZKKil3K/2t4Fup9ahbwJaMrGnx9UCOS3xEho+UXH1cH9VfqhtESUj0kG7nafFlgLOV++tyWVf9u8gfbkbmadu7frXtA+mf0Y4RZtLLvTAH1y3hpA/+oVcMahZ2PYZRrXiUg03fdrXK1Ek2FzSBV4PVAT7bl44f5cj+9lkfDMfMFRQmAFrBG0/IH2pWehcSbqrKppH7ObIjSeztK6Yrjioj1BpnOOdhiPnJTGvauJUGvh3gIBidvBlRjBgBP9v2Pz8lcSEvjyneO6c6hujPl5CGzqgUCIBv1B6Gi4P3lcwf7kfTos4NS7wwXFY3zU5nvNVhPv3CREs3HqJ4DOX2x3e7y53zpDaVpMbCajUTJAsdxkeXBy43lqVeVrnSh1Mi6dO5vgrp8Z7H6X572ieD3z0Oe+84rS2CwDprXaz0Sm4EZ5WjDZjeXC9Q5lZiPU/9D9NsyP6tNC/+50pYaVy++h/BAQ="
  # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
  - secure: "pcftJqyVo0EkttZCa/XrJYJJe7+afxBhJyswPGOyxtVnu57S+ELW4R1mtLD4dZtUWhLWTpKtKqse9Gmym7GxVLMd+wFTQGJiqGI+UA2Mk/ECF955twVIbrc4DBSuI3KSpyFtKX9X/58RBVM0VJK06eWNugh1brDGUpX/lTMJ80bQ83p3FMUEZcmIuZDpoT33SNjJN0XIFoGE+r0GYuuS28vhPREzIAOTy2FQgFlgJq5LtCIKxglSfmBniPYmFIOSbGokwNJiPXCYOukYfa/V2byDfXD9Y7Og5RL3BV3hpCphXpWQK9nwLPNlA92IPtM136PCsPn9MEe7DL0uZetT5TspK1BVydyg2lsyNgoi6+iXuRQjnPHjrzSHtJpPTysp4JVpgxWa+alDdDuPRDwJpd8ynynxal0qboBuZBPR6LyLs8i+DNjScm2UyT9A/9uZ6ehmUSTDQ4VBe5tCKStsdVJ/7i+JdGAXYHwmtFS8PU0pCrGkWhOZh83hWOlJ+Pljk7W9IzDbg6igdYPif1duqkDGWhodK/xnNIvHeR/8mtmrBwnnEsBOvAU3fVI/3JIk0fzD0yQ5Uayh8hWO1SgIAKpZAzF/NT1XYKl79XyypcASQhgYqYR8RhB/t8GRhkdq/0EMC6xXoy4ogWrFS97+HuTV3Im3boGLYKlwGq/+M1g="
  # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
  - secure: "Rf+AgQIIL6tBe4Sp0fthSAUAdPvHQXMJtcWpThoPDj17aV8M5kPjtDqVjcx7da3v/oVZ9GhxFlXNNSkQLGfxxazOLGDMljVo++4Cn3YAPDVSjdMXp3O4EEM8/mkju+Jm061DbqELppkho2x717UhBsgHGF66OOYctzCjZt/bLozBsiOReVQ48aFXF1VVMIL9SrNJcFSWVekDZyp8oE70K1PLqNpcd6CMOKn95ab/m53TCA23cggMjF0/X4jlzKURaoTJmDUdSXNW55Ll/OvaOASlJ6eRZ8yuACnYbjXcR+gdFtrXfsUFGDen3/uRRQ78XsfiYXeYcKfQlEwigxXW3Z/NC3gKwP1LR5L92L5tHXVKJvy1wrwjUasnKnJZPyzsNnTgkl1ljOsa5IMyjzIq262rUjmh7DHGR+kttUBkgFzSY3iCkDj59oirE65JZiFEFHbXBRll7AB5qRyFlhLOp4b76cR4IdRCtOVXeoTmdK5aC3q1i1OweYnHECu8EkTosi+GT8UzmWE14zzKJX7w/reFCZS1WMg3HnsQOkXfXJZfvSl2w5Se8mOtUnP20qv6pPOytWFCcJwHqac9vx9TjUOTZhYhK4/F/IX09awfQUXI2vBQrD6zKqAn291192PZ8TosNdyiK5IH/pb/UmNFz22ChT70HChsw1bvtAtY090="
```
